id: project-planning
name: Project Planning & Management
description: Tools and guidance for software project planning, feature breakdown, epic management, implementation planning, and task organization for development teams.
tags:
  [
    planning,
    project-management,
    epic,
    feature,
    implementation,
    task,
    architecture,
    technical-spike,
  ]
items:
  # Planning Chat Modes
  - path: agents/task-planner.agent.md
    kind: agent
  - path: agents/task-researcher.agent.md
    kind: agent
  - path: agents/planner.agent.md
    kind: agent
  - path: agents/plan.agent.md
    kind: agent
  - path: agents/prd.agent.md
    kind: agent
  - path: agents/implementation-plan.agent.md
    kind: agent
  - path: agents/research-technical-spike.agent.md
    kind: agent

  # Planning Instructions
  - path: instructions/task-implementation.instructions.md
    kind: instruction
  - path: instructions/spec-driven-workflow-v1.instructions.md
    kind: instruction

  # Planning Prompts
  - path: prompts/breakdown-feature-implementation.prompt.md
    kind: prompt
  - path: prompts/breakdown-feature-prd.prompt.md
    kind: prompt
  - path: prompts/breakdown-epic-arch.prompt.md
    kind: prompt
  - path: prompts/breakdown-epic-pm.prompt.md
    kind: prompt
  - path: prompts/create-implementation-plan.prompt.md
    kind: prompt
  - path: prompts/update-implementation-plan.prompt.md
    kind: prompt
  - path: prompts/create-github-issues-feature-from-implementation-plan.prompt.md
    kind: prompt
  - path: prompts/create-technical-spike.prompt.md
    kind: prompt

display:
  ordering: alpha
  show_badge: true