id: python-mcp-development
name: Python MCP Server Development
description: Complete toolkit for building Model Context Protocol (MCP) servers in Python using the official SDK with FastMCP. Includes instructions for best practices, a prompt for generating servers, and an expert chat mode for guidance.
tags: [python, mcp, model-context-protocol, fastmcp, server-development]
items:
  - path: instructions/python-mcp-server.instructions.md
    kind: instruction
  - path: prompts/python-mcp-server-generator.prompt.md
    kind: prompt
  - path: agents/python-mcp-expert.agent.md
    kind: agent
    usage: |
      recommended

      This chat mode provides expert guidance for building MCP servers in Python with FastMCP.

      This chat mode is ideal for:
      - Creating new MCP server projects with Python
      - Implementing typed tools with Pydantic models and structured output
      - Setting up stdio or streamable HTTP transports
      - Debugging type hints and schema validation issues
      - Learning Python MCP best practices with FastMCP
      - Optimizing server performance and resource management

      To get the best results, consider:
      - Using the instruction file to set context for Python/FastMCP development
      - Using the prompt to generate initial project structure with uv
      - Switching to the expert chat mode for detailed implementation help
      - Specifying whether you need stdio or HTTP transport
      - Providing details about what tools or functionality you need
      - Mentioning if you need structured output, sampling, or elicitation

display:
  ordering: manual
  show_badge: true