id: software-engineering-team
name: Software Engineering Team
description: 7 specialized agents covering the full software development lifecycle from UX design and architecture to security and DevOps.
tags: [team, enterprise, security, devops, ux, architecture, product, ai-ethics]
items:
  - path: agents/se-ux-ui-designer.agent.md
    kind: agent
    usage: |
      ## About This Collection

      This collection of 7 agents is based on learnings from [The AI-Native Engineering Flow](https://medium.com/data-science-at-microsoft/the-ai-native-engineering-flow-5de5ffd7d877) experiments at Microsoft, designed to augment software engineering teams across the entire development lifecycle.

      **Key Design Principles:**
      - **Standalone**: Each agent works independently without cross-dependencies
      - **Enterprise-ready**: Incorporates OWASP, Zero Trust, WCAG, and Well-Architected frameworks
      - **Lifecycle coverage**: From UX research → Architecture → Development → Security → DevOps

      **Agents in this collection:**
      - **SE: UX Designer** - Jobs-to-be-Done analysis and user journey mapping
      - **SE: Tech Writer** - Technical documentation, blogs, ADRs, and user guides
      - **SE: DevOps/CI** - CI/CD debugging and deployment troubleshooting
      - **SE: Product Manager** - GitHub issues with business context and acceptance criteria
      - **SE: Responsible AI** - Bias testing, accessibility (WCAG), and ethical development
      - **SE: Architect** - Architecture reviews with Well-Architected frameworks
      - **SE: Security** - OWASP Top 10, LLM/ML security, and Zero Trust

      You can use individual agents as needed or adopt the full collection for comprehensive team augmentation.
  - path: agents/se-technical-writer.agent.md
    kind: agent
  - path: agents/se-gitops-ci-specialist.agent.md
    kind: agent
  - path: agents/se-product-manager-advisor.agent.md
    kind: agent
  - path: agents/se-responsible-ai-code.agent.md
    kind: agent
  - path: agents/se-system-architecture-reviewer.agent.md
    kind: agent
  - path: agents/se-security-reviewer.agent.md
    kind: agent
display:
  ordering: manual
  show_badge: true